# Generated by Django 4.1 on 2022-08-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacos',
            name='imagem5',
            field=models.ImageField(blank=True, upload_to='fotos/espacos/imagem5'),
        ),
    ]
