# Generated by Django 4.1 on 2022-10-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_espacos_capacidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('objeto', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('abt', 'ABERTO'), ('and', 'EM ANDAMENTO'), ('ccl', 'CONCLUIDO')], default='abt', max_length=3)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.espacos')),
            ],
        ),
    ]
