# Generated by Django 4.1 on 2022-10-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_chamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
