# Generated by Django 4.1 on 2022-10-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_alter_chamado_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelusuario',
            name='status',
            field=models.CharField(choices=[('RCP', 'Recepção'), ('TOP', 'Time Operacional')], max_length=3),
        ),
    ]
