# Generated by Django 4.1 on 2022-11-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_nivelusuario_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='atualizacao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
