# Generated by Django 4.1 on 2022-11-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_chamado_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_conclusao',
            field=models.DateField(blank=True, default='2022-11-27'),
            preserve_default=False,
        ),
    ]
