# Generated by Django 4.1 on 2022-10-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='lista_participantes',
            field=models.FileField(upload_to='templates/media/pdf'),
        ),
    ]
