# Generated by Django 4.1 on 2022-10-14 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_registro_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='teste',
        ),
    ]
