# Generated by Django 4.1 on 2022-10-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_alter_registro_lista_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='lista_participantes',
            field=models.FileField(default=0, upload_to='lista_participante/%Y/%m/%d/'),
        ),
    ]
