# Generated by Django 4.1 on 2022-10-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_registro_confirmacao_email_confirmacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacao',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='check_out',
            field=models.BooleanField(default=False),
        ),
    ]
