# Generated by Django 4.1 on 2022-10-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_alter_registro_lista_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='lista_participantes',
            field=models.FileField(blank=True, upload_to='lista_participantes/%Y/%m/%d/'),
        ),
    ]
