# Generated by Django 4.1 on 2022-10-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_confirmacao_check_in_confirmacao_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacao',
            name='horario_checkin',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='horario_checkout',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='qtd_participantes',
            field=models.IntegerField(default=0),
        ),
    ]
