# Generated by Django 4.1 on 2022-10-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_confirmacao_horario_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacao',
            name='horario_checkin',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='confirmacao',
            name='horario_checkout',
            field=models.TimeField(default=None),
        ),
    ]
