# Generated by Django 4.1 on 2022-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_espacos_imagem5'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacos',
            name='capacidade',
            field=models.IntegerField(default=0),
        ),
    ]
