# Generated by Django 4.1 on 2022-10-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_alter_nivelusuario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelusuario',
            name='status',
            field=models.CharField(choices=[('RCP', 'Recepção'), ('TOP', 'Time Operacional')], default='RCP', max_length=3),
        ),
    ]
