# Generated by Django 4.1 on 2022-10-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_remove_registro_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora_fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
