# Generated by Django 4.1 on 2022-10-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_registro_data_reserva_alter_registro_hora_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='espacos',
            field=models.CharField(choices=[('Espaço01', 'Espaço01'), ('Espaço02', 'Espaço02'), ('Espaço03', 'Espaço03')], default='Espaço01', max_length=30),
        ),
    ]
