# Generated by Django 4.1 on 2022-10-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_alter_registro_espacos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='confirmacao_email',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Confirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('ativo', models.BooleanField(default=False)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reserva.registro')),
            ],
        ),
    ]
