# Generated by Django 4.1 on 2022-11-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_alter_confirmacao_horario_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacao',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.registro'),
        ),
    ]
