# Generated by Django 4.1 on 2022-11-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0012_alter_registro_espacos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservasFinalizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('agente', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('espaco', models.CharField(max_length=255)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('quantidade_de_pessoas', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='DiasDisponiveis',
        ),
        migrations.DeleteModel(
            name='DiasSemanaisDisponiveis',
        ),
        migrations.DeleteModel(
            name='HorariosDisponiveis',
        ),
    ]
