# Generated by Django 4.1 on 2022-11-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_nivelusuario_status'),
        ('reserva', '0013_reservasfinalizadas_delete_diasdisponiveis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasfinalizadas',
            name='espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.espacos'),
        ),
    ]
