# Generated by Django 4.1 on 2022-11-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_nivelusuario_status'),
        ('reserva', '0014_alter_reservasfinalizadas_espaco'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservasCanceladas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('agente', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('motivo_cancelamento', models.TextField()),
                ('data_cancelamento', models.DateField(auto_now_add=True)),
                ('hora_cancelamento', models.TimeField(auto_now_add=True)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.espacos')),
            ],
        ),
    ]
