# Generated by Django 4.1 on 2022-11-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0015_reservascanceladas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasfinalizadas',
            name='registro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reserva.registro'),
            preserve_default=False,
        ),
    ]
